<?php
if ($this->getNotification()) {
  ?>

  <div class="notification-global">
    <strong><?php echo $this->helper('index')->__('Manufacturer URL are not up to date.') ?></strong>
    <?php echo $this->helper('index')->__('Click here to go to <a href="%s">Manufacturer Management</a> and rebuild Manufacturer URLs.', $this->getUrl('manufacturer/adminhtml_manufacturer/index')); ?>
  </div>
<?php } ?>